name: Bicep-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    paths:
      - '**.bicep'
  schedule:
    - cron: '0 0 * * *' # every day at midnight
jobs:

  Bicep-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bicep CI
        uses: pchettri3/bicep-build-actions
        with:
          files: ./PAC-Autmain.bicep